### ISSUE TITLE
How to use ng-classify before all coffee files are rendered?

### ISSUE THREAD

**Issue by ramstein74** [linemanjs/lineman#288]
hello i would like to use ng-classify that processes coffee files.
but as lineman also processes coffee files, how do i use ng-classify before lineman do its job on coffee files?

Thank you

**Comment by davemo** [comment]
Hi @ramstein74, you'll need to reference the name of the grunt _task_ in `prependTasks` instead of the name of the grunt plugin (they aren't always the same). 

For reference, `grunt-ng-classify` is the name of the plugin, the name of its grunt task is `ngClassify` which you can see here: https://github.com/CaryLandholt/grunt-ng-classify/blob/master/tasks/ngClassify.coffee#L4
