### ISSUE TITLE
Allow different location of "config" folder

### ISSUE THREAD

**Issue by mitchhentges** [linemanjs/lineman#346]
Due to project structure requirements, I want to move the "config" folder to a different location (e.g. "./build/config/". Currently, lineman has a hard-coded location for "application.js/coffee" and "files.js/coffee" at "./config/".

It would be #1 if I could specify the location of "config" by manipulating options in the "Gruntfile.js" that lineman reads first

**Comment by searls** [comment]
Linemna is intentionally pretty rigid about project structure; it's the one thing we fix so that other tools can make assumptions about where things are (and what types of assets they'll find there). We do make file globs for many types of things configurable in `config/files.js`, but we encourage people to minimize their customizations.

I'm almost certain that  PR that would implement what you're asking for wouldn't catch all of the places (either in Lineman or in its various plugins) that have `config/` hardcoded. Sorry :(

**Comment by searls** [comment]
If I were in your shoes I'd just create a symlink.
