### ISSUE TITLE
Lineman production deployment issue

### ISSUE THREAD

**Issue by connienguyen2** [linemanjs/lineman#368]
I've been using Lineman with AngularJS and loving it. Everything has been working well. However, currently I'm stuck with the deployment step. I ran lineman build and copied the dist to my nginx webserver root dir. I'm able to view the web page but the api calls are not forwarded to port 8002. Hence, nothing is working. It only works with lineman run, hence node server. Please help!
in config/application.js, the config contains:
server: {
         pushState:true,
       apiProxy: {
         enabled: true,
         host: 'localhost',
         port: 8002, //Django REST APIs are running on this port
         prefix: 'api'
       }
    }

**Comment by searls** [comment]
Hi, thanks for asking your question here. Port forwarding is, by design, a feature that Lineman only implements to help with development, it is not designed to be implemented in production. Your JavaScript should make its API calls to the actual API server (on the same domain and port), in order to adhere to browsers' same-origin policies.

**Comment by connienguyen2** [comment]
Thanks for your prompt response. Looks like we'll use reverse proxy to handle this since our app is consuming APIs from multiple domains.
