### ISSUE TITLE
Update testem dependency

### ISSUE THREAD

**Issue by Tea56** [linemanjs/lineman#369]
Hi,

can you please update testem dependency from 0.7.6 to current 0.9.0-1. 

Thank you!

**Comment by jasonkarns** [comment]
If you install testem locally, lineman will use the version you install rather than the version bundled with lineman. This way you can use a newer version of testem (or any of lineman's dependencies) without waiting for an updated lineman release.

I'll keep this open since we do need to upgrade testem. But it's possible to use the latest testem without a new lineman release.

**Comment by Tea56** [comment]
Thank you. My app is holding onto 0.7.6 :D

I'll look more closely.

**Comment by jasonkarns** [comment]
I should also note that lineman won't pick up the *global* install of testem. Only a local install will override the bundled version.

**Comment by Tea56** [comment]
Thank you, got it now!
