### ISSUE TITLE
Exclude css from generated css (for a style guide page)

### ISSUE THREAD

**Issue by BurningDog** [linemanjs/lineman#383]
I've added a ```styleguide.html``` to my site, and have some css (in ```app/css/styleguide.scss```) which I'd like to manually include in the style guide html (with a ```<link>```) but not in my normal site's html. How can I exclude that scss file from being included in the generated app.css? I'm using node-sass, and have a main.scss file which explicitly imports each scss file I need for the generated ```app.css```

My ```config/files.js``` sass config looks like:

```
    sass: {
      main: "app/css/main.{sass,scss}",
      compass: true
    }
```

**Comment by searls** [comment]
I don't have a great answer to this off the top of my head (I see what you're saying but I'm struggling to visualize it). Anyone else have a moment to respond more intelligently?

**Comment by jasonkarns** [comment]
Not a very helpful answer, but a thought experiment. Since a styleguide or
pattern library is generally meant to be a standalone page(s) with base css
(and even JS), would it make more sense if the styleguide were its own
lineman app? I realize this introduces its own complexities, so I don't
mean to dismiss the underlying issue with a sweeping "separate app"
response. But might be worth it. I think it would carry other benefits as
well, like the ability to make iterations on the guide/core styles
separately from the main app(s).
